apiVersion: v1
data:
  mapRoles: "- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::299335861593:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-BCI5LQ3G7CTT\n
    \ username: system:node:{{EC2PrivateDNSName}} \n- groups:\n  - system:masters\n
    \ rolearn: arn:aws:iam::299335861593:role/UdacityFlaskDeployCBKubectlRole\n  username:
    build\n"
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-27T19:16:05Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "12324"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 6f468857-7a14-4aee-b9c8-3939ac9aeb34
