apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::299335861593:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-BCI5LQ3G7CTT
      username: system:node:{{EC2PrivateDNSName}} 
    - groups:
      - system:masters
      rolearn: arn:aws:iam::299335861593:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-27T19:16:05Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1032"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 6f468857-7a14-4aee-b9c8-3939ac9aeb34
